// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package main


import "github.com/seldonsmule/logmsg"

func (pP *MyExample) GetAuthentication() (bool, Authentication){

  var s Authentication

  pP.SetObject(&s)

  if(!pP.GetStruct("authentication", false)){
    logmsg.Print(logmsg.Error, "GetStruct(authentication) failed")
    return false, s
  }

  return true, s

}


type Authentication struct {
	AccessToken  string  `json:"access_token"`
	CreatedAt    float64 `json:"created_at"`
	ExpiresIn    float64 `json:"expires_in"`
	RefreshToken string  `json:"refresh_token"`
	TokenType    string  `json:"token_type"`
}
