// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package main


import "github.com/seldonsmule/logmsg"

func (pP *MyExample) GetVehicles() (bool, Vehicles){

  var s Vehicles

  pP.SetObject(&s)

  if(!pP.GetStruct("vehicles", false)){
    logmsg.Print(logmsg.Error, "GetStruct(vehicles) failed")
    return false, s
  }

  return true, s

}


type Vehicles struct {
	Count    float64 `json:"count"`
	Response []struct {
		APIVersion             float64     `json:"api_version"`
		BackseatToken          interface{} `json:"backseat_token"`
		BackseatTokenUpdatedAt interface{} `json:"backseat_token_updated_at"`
		CalendarEnabled        bool        `json:"calendar_enabled"`
		Color                  interface{} `json:"color"`
		DisplayName            string      `json:"display_name"`
		ID                     float64     `json:"id"`
		IDS                    string      `json:"id_s"`
		InService              bool        `json:"in_service"`
		OptionCodes            string      `json:"option_codes"`
		State                  string      `json:"state"`
		Tokens                 []string    `json:"tokens"`
		VehicleID              float64     `json:"vehicle_id"`
		Vin                    string      `json:"vin"`
	} `json:"response"`
}
